snippet_id:
  type: keyword
manual_title:
  type: keyword
manual_type:
  type: keyword
manual_version:
  type: keyword
manual_language:
  type: keyword
page_title:
  type: text
rootline:
  type: keyword
relative_url:
  type: keyword
snippet_title:
  type: text
snippet_content:
  type: text
content_hash:
  type: keyword
